[data]
cora_folder_path = "cora"

[split]
n_splits = 10
test_ratio = 0.2

[model]
n_hidden_neurons= 20
dropout = 0.5
model_save_dir = "models"
model_save_name = "model"

[train]
lr = 0.001
weight_decay = 5e-4
num_epochs = 500
batch_size = 1000