FROM python:3.11 as cora

WORKDIR /app/predict

COPY  requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x ./run.predict.sh

CMD ["/bin/bash", "./run.predict.sh"]

